name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Runs when you push to main

permissions:
  contents: write # Needed for Pages deployment

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build
        working-directory: ./peacockdating

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./peacockdating/dist
          publish_branch: gh-pages
          keep_files: false
